variables:
    IMAGE_NAME: marketer
    IMAGE_TAG: 0.0.1
    SMS_Message: "link-shortener->built-deployed"

stages:
  - Build
  - Deploy
  - Notifications

build:
    stage: Build
    image: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/repository/tech1a-docker-registry/docker:20.10.17
    services:
    - name: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/repository/tech1a-docker-registry/docker:20.10.17-dind
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
    variables:
      DOCKER_DAEMON_OPTIONS: "--insecure-registry=$DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT"

    script:
        - docker login -u "$DOCKER_PRIVATE_REGISTRY_USER" -p "$DOCKER_PRIVATE_REGISTRY_PASSWORD" "http://$DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT" 
        - docker build -t $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/$IMAGE_NAME:$IMAGE_TAG .
        - docker push $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/$IMAGE_NAME:$IMAGE_TAG
        - docker tag $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/$IMAGE_NAME:$IMAGE_TAG $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/$IMAGE_NAME:latest
        - docker push $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT/$IMAGE_NAME:latest
    retry: 2

deploy:
  stage: Deploy
  variables: 
    DOCKER_HOST: "ssh://$DOCKER_SWARM_IP"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - echo "$DOCKER_SWARM_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DOCKER_SWARM_IP >> ~/.ssh/known_hosts
  script:
    - docker stack deploy -c docker-compose.yml $IMAGE_NAME
  retry: 2

SMS:
  stage: Notifications
  image: curlimages/curl:7.84.0
  variables:
    SMSGroup_PRIVATE: '989355789980'
  script:
    - curl -X POST "http://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup_PRIVATE&body=$SMS_Message&flash=0"
  retry: 2
