variables:
    IMAGE_NAME: marketer
    IMAGE_TAG: 0.0.1
    SMS_Message: "marketer->built-deployed"
    REGISTRY_HOST: $DOCKER_PRIVATE_REGISTRY_IP:$DOCKER_PRIVATE_REGISTRY_PORT
    NAMESPACE: stg-marketer

stages:
  - Build
  - Deploy
  - Notifications

build:
    stage: Build
    image: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17
    services:
    - name: $REGISTRY_HOST/repository/tech1a-docker-registry/docker:20.10.17-dind
      alias: docker
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
    variables:
      DOCKER_DAEMON_OPTIONS: "--insecure-registry=$REGISTRY_HOST"
    script:
        - docker login -u "$DOCKER_PRIVATE_REGISTRY_USER" -p "$DOCKER_PRIVATE_REGISTRY_PASSWORD" "http://$REGISTRY_HOST"
        - docker build . -t $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest -t $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$CI_PIPELINE_ID
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:latest
        - docker push $REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$CI_PIPELINE_ID

deploy-staging:
  stage: Deploy
  image: dtzar/helm-kubectl:3.0.3
  script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$K8S_STG" | base64 -d > ~/.kube/config
    - kubectl -n "$NAMESPACE" apply -f deployment/stage/stage.yaml
    - kubectl set image -n "$NAMESPACE" deployment/marketer-api marketer-api=$REGISTRY_HOST/repository/tech1a-docker-registry/$IMAGE_NAME:$CI_PIPELINE_ID

SMS:
  stage: Notifications
  image: curlimages/curl:7.84.0
  variables:
    SMSGroup_PRIVATE: '989355789980'
  script:
    - curl -X POST "http://my.candoosms.com/services/URLService/URN/?username=$SMS_PROVIDER_USER&password=$SMS_PROVIDER_PASSWORD&command=send&src=$SMS_SEND_SRC&destinations=$SMSGroup_PRIVATE&body=$SMS_Message&flash=0"
  retry: 2
