kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-api
  labels:
    name: marketer-api
    instance: marketer-api
data:
  VERSION: "0.0.1"
  MONGO_CONNECTION_STRING: "mongodb://root:3tliSqt3tDD5Bg@mongo-marketer-headless.stg-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer API"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  ISSUER: "https://cluster.tech1a.co"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-api
spec:
  selector:
    matchLabels:
      app: marketer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-api
    spec:
      containers:
      - name: marketer-api
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-api:latest"
        envFrom:
          - configMapRef:
              name: marketer-api
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-api
  labels:
    app: marketer-api
spec:
  type: ClusterIP
  selector:
    app: marketer-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-api
spec:
  ingressClassName: nginx
  rules:
    - host: stgmarketer-api.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-api
              port:
                number: 80
