kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-api
  labels:
    name: marketer-api
    instance: marketer-api
data:
  VERSION: "0.0.1"
  MONGO_CONNECTION_STRING: "mongodb://root:3tliSqt3tDD5Bg@mongo-marketer-headless.stg-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer API"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  JWKS: {"keys":[{"kty":"RSA","use":"sig","kid":"49C1F3BFFCBF7F5450979CECFDC4B0D177DA8164RS256","x5t":"ScHzv_y_f1RQl5zs_cSw0XfagWQ","e":"AQAB","n":"tZC4age3I9cIj_Utc2lzzCkvYj2bAJcx11rrkQMACbRU--NS7UUqcfZsxBZbVvgZTUPkPHcLmImBoJnw4v17eTJZKkkYn7HjJQLbnuczzAmdypOMYUzgOgRjgYasknvJLkg-0KMZ1uj_8R7QhOziApm9qtCH5GwV5_CpRPtAhT5tfVB_yyFw7p_1putsx6stYzgaW_5FoU97DDkF2wmtxf3mpNgUSzp7dBoSTw8YCu-jqh8iJhfvUOeuC_jR1TgGLDjU9WYTTWYFh09669tHYEqeXwDb1R7W3H3NfKQr3Wamrab84TRmvApQQUSh1IPxMJB9xR471wo5YXXsNCryuQ","x5c":["MIIGYDCCBUigAwIBAgIQEfF3RPSDUtZtUlgFMf5YqzANBgkqhkiG9w0BAQsFADCBhTELMAkGA1UEBhMCUEwxIjAgBgNVBAoTGVVuaXpldG8gVGVjaG5vbG9naWVzIFMuQS4xJzAlBgNVBAsTHkNlcnR1bSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQ2VydHVtIERvbWFpbiBWYWxpZGF0aW9uIENBIFNIQTIwHhcNMjIwOTA0MTM1MjAwWhcNMjMwOTA0MTM1MTU5WjAWMRQwEgYDVQQDDAsqLnRlY2gxYS5jbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALWQuGoHtyPXCI/1LXNpc8wpL2I9mwCXMdda65EDAAm0VPvjUu1FKnH2bMQWW1b4GU1D5Dx3C5iJgaCZ8OL9e3kyWSpJGJ\u002Bx4yUC257nM8wJncqTjGFM4DoEY4GGrJJ7yS5IPtCjGdbo//Ee0ITs4gKZvarQh\u002BRsFefwqUT7QIU\u002BbX1Qf8shcO6f9abrbMerLWM4Glv\u002BRaFPeww5BdsJrcX95qTYFEs6e3QaEk8PGArvo6ofIiYX71Dnrgv40dU4Biw41PVmE01mBYdPeuvbR2BKnl8A29Ue1tx9zXykK91mpq2m/OE0ZrwKUEFEodSD8TCQfcUeO9cKOWF17DQq8rkCAwEAAaOCAzgwggM0MAwGA1UdEwEB/wQCMAAwMgYDVR0fBCswKTAnoCWgI4YhaHR0cDovL2NybC5jZXJ0dW0ucGwvZHZjYXNoYTIuY3JsMHEGCCsGAQUFBwEBBGUwYzArBggrBgEFBQcwAYYfaHR0cDovL2R2Y2FzaGEyLm9jc3AtY2VydHVtLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL3JlcG9zaXRvcnkuY2VydHVtLnBsL2R2Y2FzaGEyLmNlcjAfBgNVHSMEGDAWgBTlMa2/OhGW9IO8UDzUt5CbkO7eJTAdBgNVHQ4EFgQUVpau/fkXDgXObhLU1ADBgoTHlowwHQYDVR0SBBYwFIESZHZjYXNoYTJAY2VydHVtLnBsMEsGA1UdIAREMEIwCAYGZ4EMAQIBMDYGCyqEaAGG9ncCBQEDMCcwJQYIKwYBBQUHAgEWGWh0dHBzOi8vd3d3LmNlcnR1bS5wbC9DUFMwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA4GA1UdDwEB/wQEAwIFoDAhBgNVHREEGjAYggsqLnRlY2gxYS5jb4IJdGVjaDFhLmNvMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdgBVgdTCFpA2AUrqC5tXPFPwwOQ4eHAlCBcvo6odBxPTDAAAAYMIxcBrAAAEAwBHMEUCIQCoaBBAkJqOBfY7wi4k80xRiHRtv4cpRMCnY\u002BpRphsyJQIgc/ujvwzEaVv19DCRe4SOM3D2ixys2cjEHirRphNIohMAdgCt9776fP8QyIudPZwePhhqtGcpXc\u002BxDCTKhYY069yCigAAAYMIxcBDAAAEAwBHMEUCIQDWzBu/dfasatNaMjd7TcHLc0oXKw3K0oCV083KpkTACAIgbP61I6kg4LxJhjr3DzUJcyCLoZRbYLNAnvPM5SaNrQ4AdQB6MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAYMIxcC6AAAEAwBGMEQCIEuZm1yYK3ySLEHBbzur8pmYu\u002BrcU8\u002BYAcR9q8npwSI9AiBbdbfyEYXJFEd2tdHYqyfka3OY\u002BBAEwOms\u002BkhrrztuMTANBgkqhkiG9w0BAQsFAAOCAQEAAA4k428eRjyu/NZSpX9K2H4m\u002BZ4/1Pb4CrzqUnN\u002BDWExFAHjZf24fSR6ueOFJ2HdDmbvEtjt6tR\u002B2u\u002BBYykoyfXfCJ4YR8HoFQBQQvANcs2g24Y0n0u/JPuUV\u002BmEvNjaO0XbaxUDMUoJeRiimpd7mbZXZSXgq3FEvryaDGDNyvLBh6JymIp77xm/YYpBWekk0PFpGWOHdOlAVFXr2KHGeXyFi3aVQCxZM/vag5GJuotGgj2SBvh82Tbj9h\u002BKVOTFVgvXUiUa/tbgK\u002B7Nwq0WWiz1ZeX20bQnUdfwya2I38t2ltKlqzyByxWF50A9aYTL9h1Z8o7sF6aOSq3lTR2xYA=="],"alg":"RS256"},{"kty":"RSA","use":"sig","kid":"2409BFB326FD14C1CABBB7CE04196685","e":"AQAB","n":"s9ZGBddXkYSuAE1tSha30i-RVuzU4SpDLofYmpJFJV-bFnBgSoz_lD20c5YEZuDIhyrx7-sIblEFIr_x0FaymwuD0J5xaeGndV_XoUVnVK9HG_Sq-vVJnWpsFwUwJ9LfQUdiN_VQ08K05sq8lMaPyzK0_ms1HNucTkKv0q5EGaqQc5Ow1hFdUtFEa-Gsoq4hAQH0ZdKO3IoUwkZETyeQeRm6lJNNlH-gA0Y5OFLR6WNsDYxSn5OKk4n5ITSS0rkMzywXo-5pHX-zwQ-m8ysULOqSTJpKlGSm3kXC3gGOphHzM1vUYPpOKevLj-TMAPF-GMaHCvPXZWZ2nPF3zMJ-JQ","alg":"RS256"}]}
  ISSUER: "https://cluster.tech1a.co"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-api
spec:
  selector:
    matchLabels:
      app: marketer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-api
    spec:
      containers:
      - name: marketer-api
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-api:latest"
        envFrom:
          - configMapRef:
              name: marketer-api
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-api
  labels:
    app: marketer-api
spec:
  type: ClusterIP
  selector:
    app: marketer-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-api
spec:
  ingressClassName: nginx
  rules:
    - host: stgmarketer-api.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-api
              port:
                number: 80
