kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-api
  labels:
    name: marketer-api
    instance: marketer-api
data:
  VERSION: "0.0.1"
  MONGO_CONNECTION_STRING: "mongodb://root:3tliSqt3tDD5Bg@mongo-marketer-headless.stg-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer API"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  JWKS: "{"keys":[{"kty":"RSA","use":"sig","kid":"49C1F3BFFCBF7F5450979CECFDC4B0D177DA8164RS256","x5t":"ScHzv_y_f1RQl5zs_cSw0XfagWQ","e":"AQAB","n":"tZC4age3I9cIj_Utc2lzzCkvYj2bAJcx11rrkQMACbRU--NS7UUqcfZsxBZbVvgZTUPkPHcLmImBoJnw4v17eTJZKkkYn7HjJQLbnuczzAmdypOMYUzgOgRjgYasknvJLkg-0KMZ1uj_8R7QhOziApm9qtCH5GwV5_CpRPtAhT5tfVB_yyFw7p_1putsx6stYzgaW_5FoU97DDkF2wmtxf3mpNgUSzp7dBoSTw8YCu-jqh8iJhfvUOeuC_jR1TgGLDjU9WYTTWYFh09669tHYEqeXwDb1R7W3H3NfKQr3Wamrab84TRmvApQQUSh1IPxMJB9xR471wo5YXXsNCryuQ","x5c":["MIIGYDCCBUigAwIBAgIQEfF3RPSDUtZtUlgFMf5YqzANBgkqhkiG9w0BAQsFADCBhTELMAkGA1UEBhMCUEwxIjAgBgNVBAoTGVVuaXpldG8gVGVjaG5vbG9naWVzIFMuQS4xJzAlBgNVBAsTHkNlcnR1bSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEpMCcGA1UEAxMgQ2VydHVtIERvbWFpbiBWYWxpZGF0aW9uIENBIFNIQTIwHhcNMjIwOTA0MTM1MjAwWhcNMjMwOTA0MTM1MTU5WjAWMRQwEgYDVQQDDAsqLnRlY2gxYS5jbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALWQuGoHtyPXCI/1LXNpc8wpL2I9mwCXMdda65EDAAm0VPvjUu1FKnH2bMQWW1b4GU1D5Dx3C5iJgaCZ8OL9e3kyWSpJGJ+x4yUC257nM8wJncqTjGFM4DoEY4GGrJJ7yS5IPtCjGdbo//Ee0ITs4gKZvarQh+RsFefwqUT7QIU+bX1Qf8shcO6f9abrbMerLWM4Glv+RaFPeww5BdsJrcX95qTYFEs6e3QaEk8PGArvo6ofIiYX71Dnrgv40dU4Biw41PVmE01mBYdPeuvbR2BKnl8A29Ue1tx9zXykK91mpq2m/OE0ZrwKUEFEodSD8TCQfcUeO9cKOWF17DQq8rkCAwEAAaOCAzgwggM0MAwGA1UdEwEB/wQCMAAwMgYDVR0fBCswKTAnoCWgI4YhaHR0cDovL2NybC5jZXJ0dW0ucGwvZHZjYXNoYTIuY3JsMHEGCCsGAQUFBwEBBGUwYzArBggrBgEFBQcwAYYfaHR0cDovL2R2Y2FzaGEyLm9jc3AtY2VydHVtLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL3JlcG9zaXRvcnkuY2VydHVtLnBsL2R2Y2FzaGEyLmNlcjAfBgNVHSMEGDAWgBTlMa2/OhGW9IO8UDzUt5CbkO7eJTAdBgNVHQ4EFgQUVpau/fkXDgXObhLU1ADBgoTHlowwHQYDVR0SBBYwFIESZHZjYXNoYTJAY2VydHVtLnBsMEsGA1UdIAREMEIwCAYGZ4EMAQIBMDYGCyqEaAGG9ncCBQEDMCcwJQYIKwYBBQUHAgEWGWh0dHBzOi8vd3d3LmNlcnR1bS5wbC9DUFMwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA4GA1UdDwEB/wQEAwIFoDAhBgNVHREEGjAYggsqLnRlY2gxYS5jb4IJdGVjaDFhLmNvMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdgBVgdTCFpA2AUrqC5tXPFPwwOQ4eHAlCBcvo6odBxPTDAAAAYMIxcBrAAAEAwBHMEUCIQCoaBBAkJqOBfY7wi4k80xRiHRtv4cpRMCnY+pRphsyJQIgc/ujvwzEaVv19DCRe4SOM3D2ixys2cjEHirRphNIohMAdgCt9776fP8QyIudPZwePhhqtGcpXc+xDCTKhYY069yCigAAAYMIxcBDAAAEAwBHMEUCIQDWzBu/dfasatNaMjd7TcHLc0oXKw3K0oCV083KpkTACAIgbP61I6kg4LxJhjr3DzUJcyCLoZRbYLNAnvPM5SaNrQ4AdQB6MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAYMIxcC6AAAEAwBGMEQCIEuZm1yYK3ySLEHBbzur8pmYu+rcU8+YAcR9q8npwSI9AiBbdbfyEYXJFEd2tdHYqyfka3OY+BAEwOms+khrrztuMTANBgkqhkiG9w0BAQsFAAOCAQEAAA4k428eRjyu/NZSpX9K2H4m+Z4/1Pb4CrzqUnN+DWExFAHjZf24fSR6ueOFJ2HdDmbvEtjt6tR+2u+BYykoyfXfCJ4YR8HoFQBQQvANcs2g24Y0n0u/JPuUV+mEvNjaO0XbaxUDMUoJeRiimpd7mbZXZSXgq3FEvryaDGDNyvLBh6JymIp77xm/YYpBWekk0PFpGWOHdOlAVFXr2KHGeXyFi3aVQCxZM/vag5GJuotGgj2SBvh82Tbj9h+KVOTFVgvXUiUa/tbgK+7Nwq0WWiz1ZeX20bQnUdfwya2I38t2ltKlqzyByxWF50A9aYTL9h1Z8o7sF6aOSq3lTR2xYA=="],"alg":"RS256"},{"kty":"RSA","use":"sig","kid":"91DF7D4D4140ED7B6EBD0B1D9BE8C2EF","e":"AQAB","n":"67qbw1RlmIlX7M22AWVk1MkxCUkluo_2FPe4tmrzmitV2MHyNaL2uGrIcnU3dFreEWcM13dcqLsmKsyxHu9nmDgCmJDZ-do6H7VC32mdD2AsBOF5RD7nAl8DbcA2eqMVxldkfDa4Qb8W-WcsxIcmZaDmquCb_jRsSXSLXaTK-iivi1AoeFXM2zWYXWzN_vno_oyGrvY_Op5N9uE1kX8SA40-YG1-PXLCmFJNt_2VN7DuVj870qUegMFs0JkdKqiTfeWrsdG_x3L7pGt0TKN2OWQACT3vUsZyVYov7GGoxl2q_2xpFLHQWJGvDHqSjfiLZA12seOJY72_DHvUSMcrVQ","alg":"RS256"}]}"
  ISSUER: "https://cluster.tech1a.co"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-api
spec:
  selector:
    matchLabels:
      app: marketer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-api
    spec:
      containers:
      - name: marketer-api
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-api:latest"
        envFrom:
          - configMapRef:
              name: marketer-api
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-api
  labels:
    app: marketer-api
spec:
  type: ClusterIP
  selector:
    app: marketer-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-api
spec:
  ingressClassName: nginx
  rules:
    - host: stgmarketer-api.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-api
              port:
                number: 80
